packages:
  - name: sample
    actions:
      - name: age
        main: dist/packages/sample/age/src/age.main
        runtime: 'nodejs:default'
      - name: name
        main: dist/packages/sample/name/src/name.main
        runtime: 'nodejs:default'
