packages:
  - name: sample
    actions:
      - name: age
        main: dist/index.main
        runtime: 'nodejs:default'
      - name: name
        main: dist/index.main
        runtime: 'nodejs:default'
